# swagger configuration file
# values in the swagger hash are system configuration for swagger-node
swagger:
  fittingsDirs: [ fittings, node_modules ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers
  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:
    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ mocks ]
      controllersDirs: [ controllers ]
      controllersInterface: auto-detect
    _swagger_validate:
      name: swagger_validator
    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: error_logger
      - swagger_cors
      - swagger_security
      - swagger_params_parser
      - _swagger_validate
      - express_compatibility
      - _router
    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      - swagger_cors
      - swagger_raw
# any other values in this file are just loaded into the config for application access...